
[Interface]
PrivateKey = s+x+JEgqXpjNY/mv4jVewvzER4fiiatH63OYPP47SmA=
Address = fdaa:1d:2d88:a7b:9285:fd6e:479:4e02/120
DNS = fdaa:1d:2d88::3

[Peer]
PublicKey = qD38OvXdLJwjXWALqUuDpERlNS4FzFlrwG/c2roQZRs=
AllowedIPs = fdaa:1d:2d88::/48
Endpoint = yyz2.gateway.6pn.dev:51820
PersistentKeepalive = 15

