"""Dependency-light DTO schemas — re-exports for convenience.

Import DTOs from this package instead of ``wikimind.models`` when you only
need Pydantic request/response schemas and want to avoid pulling in
SQLModel / database dependencies.

Example::

    from wikimind.models.dto import ArticleResponse, IngestURLRequest
"""

from wikimind.models.dto.admin import (
    AdminActionResult,
    AdminUserDetail,
    AdminUserSummary,
    EligibleConcept,
    HealthReport,
    HealthSummaryResponse,
    OrphanArticle,
    RecentSourceEntry,
    StuckSource,
    SystemStats,
    WikiHealthReport,
    ZombieSource,
)
from wikimind.models.dto.auth import (
    DeleteAccountResponse,
    MagicLinkRequest,
    MagicLinkResponse,
    MagicLinkVerifyRequest,
    MagicLinkVerifyResponse,
    OAuthTokenResponse,
    OAuthUserInfo,
    TokenCreateRequest,
    TokenCreateResponse,
    UserProfileResponse,
)
from wikimind.models.dto.capture import (
    AmbientAdapterConfigureRequest,
    AmbientAdapterListResponse,
    AmbientAdapterStatusResponse,
    AmbientPollResponse,
    CaptureDiscardResponse,
    CaptureIngestResponse,
    CaptureListResponse,
    CaptureRequest,
    CaptureResponse,
    DiscardCaptureRequest,
    RssFeedListResponse,
    RssFeedRequest,
    RssFeedResponse,
    RssFeedToggleRequest,
    RssPollResponse,
)
from wikimind.models.dto.common import TagResponse
from wikimind.models.dto.compilation import (
    AnswerCompilationResult,
    AnswerFrontmatter,
    ApproveDraftRequest,
    ApproveDraftResponse,
    CompilationDraftResponse,
    CompilationResult,
    CompilationSchemaResponse,
    CompiledClaimDTO,
    ConceptCompilationResult,
    ConceptFrontmatter,
    CreateCompilationSchemaRequest,
    IndexFrontmatter,
    MetaFrontmatter,
    RejectDraftResponse,
    SourceCompilationResult,
    SourceFrontmatter,
    SynthesisCompilationResult,
    SynthesisFrontmatter,
    TypedBacklinkSuggestion,
    UpdateCompilationSchemaRequest,
)
from wikimind.models.dto.ingest import (
    ArticleSourceSummary,
    DocumentChunk,
    IngestTextRequest,
    IngestURLRequest,
    LinkedArticleSummary,
    NormalizedDocument,
    PipelineStep,
    SourceContentResponse,
    SourceDetailResponse,
    SourceImageEntry,
    SourceResponse,
)
from wikimind.models.dto.lint import (
    DismissFindingResponse,
    JobTriggerResponse,
    LinterContradiction,
    LinterResult,
    LintRunResponse,
)
from wikimind.models.dto.llm import (
    CompletionRequest,
    CompletionResponse,
    LLMProviderStatus,
    LLMTraceListResponse,
    LLMTraceResponse,
)
from wikimind.models.dto.mcp import (
    MCPTokenCreateRequest,
    MCPTokenCreateResponse,
    MCPTokenResponse,
    MCPTokenRevokeResponse,
)

# Also re-export QueryResult from query module
from wikimind.models.dto.query import (
    AskResponse,
    CitationArticleRef,
    CitationResponse,
    ConversationDetail,
    ConversationResponse,
    ConversationSummary,
    CrystallizeResponse,
    FileBackArticleRef,
    FileBackResult,
    FileBackSelectionRequest,
    ForkRequest,
    QueryRequest,
    QueryResponse,
    QueryResult,
    TurnSelection,
    WikiWorthinessScore,
)
from wikimind.models.dto.sharing import (
    CreateShareLinkRequest,
    ExportResponse,
    PublicArticleResponse,
    ShareLinkResponse,
    WikiExportResponse,
)
from wikimind.models.dto.synthesis import (
    CreateSynthesisRequest,
    SynthesisConfirmRequest,
    SynthesisConfirmResponse,
    SynthesisPreviewRequest,
    SynthesisPreviewResponse,
    SynthesisRefineRequest,
    SynthesisRefineResponse,
    SynthesisResponse,
    SynthesisSuggestion,
)
from wikimind.models.dto.tags import (
    ArticleTagResponse,
    CreateSavedSearchRequest,
    CreateTagRequest,
    SavedSearchResponse,
    TagArticleRequest,
)
from wikimind.models.dto.wiki import (
    ArticleDownloadResponse,
    ArticleEditRequest,
    ArticleRelationshipsResponse,
    ArticleResponse,
    ArticleSummaryResponse,
    BacklinkEntry,
    ConceptDetailResponse,
    ConceptResponse,
    ContradictionResolutionOption,
    ContradictionResponse,
    CreateStubRequest,
    CreateStubResponse,
    DeleteConfirmation,
    EmbeddingStats,
    FacetBucket,
    FacetGroup,
    FacetResponse,
    FTSResultItem,
    GraphEdge,
    GraphNode,
    GraphResponse,
    RebuildConceptsResponse,
    RecompileResponse,
    RefreshArticleResponse,
    RelationshipEdge,
    ResolveContradictionBody,
    ResolveContradictionRequest,
    ResolveContradictionResponse,
    SavedSearchExecuteResponse,
    SearchResponse,
    SearchResult,
    WikilinkMatch,
)

__all__ = [
    # admin
    "AdminActionResult",
    "AdminUserDetail",
    "AdminUserSummary",
    # capture
    "AmbientAdapterConfigureRequest",
    "AmbientAdapterListResponse",
    "AmbientAdapterStatusResponse",
    "AmbientPollResponse",
    # compilation
    "AnswerCompilationResult",
    "AnswerFrontmatter",
    "ApproveDraftRequest",
    "ApproveDraftResponse",
    # wiki
    "ArticleDownloadResponse",
    "ArticleEditRequest",
    "ArticleRelationshipsResponse",
    "ArticleResponse",
    # ingest
    "ArticleSourceSummary",
    "ArticleSummaryResponse",
    # tags
    "ArticleTagResponse",
    # query
    "AskResponse",
    "BacklinkEntry",
    "CaptureDiscardResponse",
    "CaptureIngestResponse",
    "CaptureListResponse",
    "CaptureRequest",
    "CaptureResponse",
    "CitationArticleRef",
    "CitationResponse",
    "CompilationDraftResponse",
    "CompilationResult",
    "CompilationSchemaResponse",
    "CompiledClaimDTO",
    # llm
    "CompletionRequest",
    "CompletionResponse",
    "ConceptCompilationResult",
    "ConceptDetailResponse",
    "ConceptFrontmatter",
    "ConceptResponse",
    "ContradictionResolutionOption",
    "ContradictionResponse",
    "ConversationDetail",
    "ConversationResponse",
    "ConversationSummary",
    "CreateCompilationSchemaRequest",
    "CreateSavedSearchRequest",
    # sharing
    "CreateShareLinkRequest",
    "CreateStubRequest",
    "CreateStubResponse",
    # synthesis
    "CreateSynthesisRequest",
    "CreateTagRequest",
    "CrystallizeResponse",
    # auth
    "DeleteAccountResponse",
    "DeleteConfirmation",
    "DiscardCaptureRequest",
    # lint
    "DismissFindingResponse",
    "DocumentChunk",
    "EligibleConcept",
    "EmbeddingStats",
    "ExportResponse",
    "FTSResultItem",
    "FacetBucket",
    "FacetGroup",
    "FacetResponse",
    "FileBackArticleRef",
    "FileBackResult",
    "FileBackSelectionRequest",
    "ForkRequest",
    "GraphEdge",
    "GraphNode",
    "GraphResponse",
    "HealthReport",
    "HealthSummaryResponse",
    "IndexFrontmatter",
    "IngestTextRequest",
    "IngestURLRequest",
    "JobTriggerResponse",
    "LLMProviderStatus",
    "LLMTraceListResponse",
    "LLMTraceResponse",
    "LinkedArticleSummary",
    "LintRunResponse",
    "LinterContradiction",
    "LinterResult",
    # mcp
    "MCPTokenCreateRequest",
    "MCPTokenCreateResponse",
    "MCPTokenResponse",
    "MCPTokenRevokeResponse",
    "MagicLinkRequest",
    "MagicLinkResponse",
    "MagicLinkVerifyRequest",
    "MagicLinkVerifyResponse",
    "MetaFrontmatter",
    "NormalizedDocument",
    "OAuthTokenResponse",
    "OAuthUserInfo",
    "OrphanArticle",
    "PipelineStep",
    "PublicArticleResponse",
    "QueryRequest",
    "QueryResponse",
    "QueryResult",
    "RebuildConceptsResponse",
    "RecentSourceEntry",
    "RecompileResponse",
    "RefreshArticleResponse",
    "RejectDraftResponse",
    "RelationshipEdge",
    "ResolveContradictionBody",
    "ResolveContradictionRequest",
    "ResolveContradictionResponse",
    "RssFeedListResponse",
    "RssFeedRequest",
    "RssFeedResponse",
    "RssFeedToggleRequest",
    "RssPollResponse",
    "SavedSearchExecuteResponse",
    "SavedSearchResponse",
    "SearchResponse",
    "SearchResult",
    "ShareLinkResponse",
    "SourceCompilationResult",
    "SourceContentResponse",
    "SourceDetailResponse",
    "SourceFrontmatter",
    "SourceImageEntry",
    "SourceResponse",
    "StuckSource",
    "SynthesisCompilationResult",
    "SynthesisConfirmRequest",
    "SynthesisConfirmResponse",
    "SynthesisFrontmatter",
    "SynthesisPreviewRequest",
    "SynthesisPreviewResponse",
    "SynthesisRefineRequest",
    "SynthesisRefineResponse",
    "SynthesisResponse",
    "SynthesisSuggestion",
    "SystemStats",
    "TagArticleRequest",
    "TagResponse",
    "TokenCreateRequest",
    "TokenCreateResponse",
    "TurnSelection",
    "TypedBacklinkSuggestion",
    "UpdateCompilationSchemaRequest",
    "UserProfileResponse",
    "WikiExportResponse",
    "WikiHealthReport",
    "WikiWorthinessScore",
    "WikilinkMatch",
    "ZombieSource",
]

# Resolve forward references now that all DTO modules are imported.
# SavedSearchExecuteResponse.saved_search uses forward-ref to SavedSearchResponse
SavedSearchExecuteResponse.model_rebuild()
