#!/usr/bin/env python3
"""Regenerate the Make targets section in `README.md` from `Makefile`.

Parses the Makefile for:

- Section headings declared as ``##@ <Section Name>``
- Target lines of the form ``target: ...  ## <description>``

Generates a markdown table grouped by section and replaces the content
between ``<!-- BEGIN make-targets -->`` and ``<!-- END make-targets -->``
in README.md.

Examples:
    python scripts/regenerate_readme_targets.py
    python scripts/regenerate_readme_targets.py --check
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MAKEFILE = REPO_ROOT / "Makefile"
README = REPO_ROOT / "README.md"

BEGIN_MARKER = "<!-- BEGIN make-targets -->"
END_MARKER = "<!-- END make-targets -->"

SECTION_RE = re.compile(r"^##@\s*(.+?)\s*$")
TARGET_RE = re.compile(r"^([a-zA-Z][a-zA-Z0-9_-]*)\s*:.*##\s+(.+?)\s*$")


@dataclass
class Section:
    """A group of Make targets under a single `##@` heading."""

    name: str
    targets: list[tuple[str, str]] = field(default_factory=list)


def parse_makefile(makefile: Path) -> list[Section]:
    """Parse a Makefile into sections of documented targets.

    Targets outside any `##@` section are collected under a synthetic
    "General" section.

    Args:
        makefile: Path to the Makefile.

    Returns:
        A list of sections in the order they appear in the file.
    """
    sections: list[Section] = []
    current = Section(name="General")

    for line in makefile.read_text(encoding="utf-8").splitlines():
        section_match = SECTION_RE.match(line)
        if section_match:
            if current.targets:
                sections.append(current)
            current = Section(name=section_match.group(1))
            continue

        target_match = TARGET_RE.match(line)
        if target_match:
            name = target_match.group(1)
            description = target_match.group(2)
            current.targets.append((name, description))

    if current.targets:
        sections.append(current)

    return sections


def render_block(sections: list[Section]) -> str:
    """Render the markdown block for the make-targets section.

    Args:
        sections: Parsed sections from the Makefile.

    Returns:
        The markdown content that goes between the begin/end markers.
    """
    lines: list[str] = [
        "<!-- (auto-generated by scripts/regenerate_readme_targets.py) -->",
        "",
    ]
    for section in sections:
        if not section.targets:
            continue
        lines.append(f"### {section.name}")
        lines.append("")
        lines.append("| Target | Description |")
        lines.append("|--------|-------------|")
        for name, description in section.targets:
            lines.append(f"| `make {name}` | {description} |")
        lines.append("")
    return "\n".join(lines)


def splice(readme_text: str, block: str) -> str:
    """Replace the BEGIN/END marker block in README content with `block`.

    Args:
        readme_text: Full existing README content.
        block: New marker-block content (no markers included).

    Returns:
        The updated README content.

    Raises:
        ValueError: If the begin or end marker is missing.
    """
    if BEGIN_MARKER not in readme_text or END_MARKER not in readme_text:
        raise ValueError(
            f"README.md is missing markers. Add:\n"
            f"  {BEGIN_MARKER}\n"
            f"  {END_MARKER}\n"
            f"where the make-targets table should appear."
        )

    before, rest = readme_text.split(BEGIN_MARKER, 1)
    _, after = rest.split(END_MARKER, 1)

    return f"{before}{BEGIN_MARKER}\n{block}\n{END_MARKER}{after}"


def main() -> int:
    """Entry point for the README make-targets regenerator."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the committed README matches the generated block.",
    )
    args = parser.parse_args()

    sections = parse_makefile(MAKEFILE)
    block = render_block(sections)

    readme_text = README.read_text(encoding="utf-8")
    try:
        new_text = splice(readme_text, block)
    except ValueError as exc:
        print(f"ERROR {exc}", file=sys.stderr)
        return 2

    if args.check:
        if readme_text == new_text:
            print(f"OK   {README} make-targets section is in sync.")
            return 0
        print(
            f"DRIFT {README} make-targets section is out of date.\n"
            f"      Regenerate with: make regenerate-readme-targets && git add {README}",
            file=sys.stderr,
        )
        return 1

    if readme_text == new_text:
        print(f"OK   {README} make-targets section already in sync.")
        return 0

    README.write_text(new_text, encoding="utf-8")
    total = sum(len(s.targets) for s in sections)
    print(f"WROTE {README} ({total} targets in {len(sections)} sections)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
