#!/usr/bin/env python3
"""Regenerate `docs/adr/README.md` from the ADR files on disk.

Walks `docs/adr/adr-*.md`, parses the title line (`# ADR-NNN: Title`) and
the "## Status" section, then rewrites the index table.

Run directly to update the file, or with `--check` to verify it is in sync
(used by pre-commit and CI).

Examples:
    python scripts/regenerate_adr_index.py
    python scripts/regenerate_adr_index.py --check
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ADR_DIR = REPO_ROOT / "docs" / "adr"
INDEX_FILE = ADR_DIR / "README.md"

ADR_FILENAME_RE = re.compile(r"^adr-(\d+)-.*\.md$")
TITLE_RE = re.compile(r"^#\s*ADR-(\d+):\s*(.+?)\s*$")
STATUS_HEADING_RE = re.compile(r"^##\s+Status\s*$", re.IGNORECASE)

HEADER = """# Architecture Decision Records

This directory contains the architectural decisions for WikiMind.
Each ADR documents a single significant decision, the alternatives
considered, and the consequences.

## Index

| ADR | Title | Status |
|-----|-------|--------|
"""

FOOTER = """
## ADR Format

Each ADR follows a consistent structure:

- **Status** — Accepted, Proposed, Superseded, or Deprecated
- **Context** — The problem or decision point
- **Decision** — What was chosen and why
- **Alternatives Considered** — What was evaluated and rejected
- **Consequences** — What this enables, constrains, or risks

*This index is auto-generated by `scripts/regenerate_adr_index.py` — do not edit by hand.*
"""


@dataclass(frozen=True)
class ADR:
    """A parsed Architecture Decision Record."""

    number: str
    title: str
    status: str
    filename: str


def parse_adr(path: Path) -> ADR:
    """Parse a single ADR markdown file.

    Args:
        path: Path to an `adr-NNN-*.md` file.

    Returns:
        A parsed ADR with number, title, status, and filename.

    Raises:
        ValueError: If the file's title line or status section cannot be parsed.
    """
    lines = path.read_text(encoding="utf-8").splitlines()

    # Find the title on the first non-empty line.
    title_line = next((ln for ln in lines if ln.strip()), "")
    title_match = TITLE_RE.match(title_line)
    if not title_match:
        raise ValueError(f"{path.name}: first line does not match '# ADR-NNN: Title'")

    number = title_match.group(1)
    title = title_match.group(2)

    # Find the Status section and read the first non-empty line below it.
    status = "Unknown"
    for idx, line in enumerate(lines):
        if STATUS_HEADING_RE.match(line):
            for follow in lines[idx + 1 :]:
                if follow.strip():
                    status = follow.strip()
                    break
            break

    return ADR(number=number, title=title, status=status, filename=path.name)


def collect_adrs(adr_dir: Path) -> list[ADR]:
    """Collect and parse all ADR files in a directory, sorted by number.

    Args:
        adr_dir: Directory containing `adr-NNN-*.md` files.

    Returns:
        A list of parsed ADRs sorted by their numeric ID.
    """
    adrs: list[ADR] = []
    for path in sorted(adr_dir.glob("adr-*.md")):
        if not ADR_FILENAME_RE.match(path.name):
            continue
        adrs.append(parse_adr(path))
    adrs.sort(key=lambda a: int(a.number))
    return adrs


def render_index(adrs: list[ADR]) -> str:
    """Render the markdown index file content.

    Args:
        adrs: Parsed ADRs in the desired display order.

    Returns:
        The full content of `docs/adr/README.md`.
    """
    rows = [f"| [{adr.number}]({adr.filename}) | {adr.title} | {adr.status} |" for adr in adrs]
    return HEADER + "\n".join(rows) + "\n" + FOOTER


def main() -> int:
    """Entry point for the regenerate script."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the committed index matches the generated content.",
    )
    args = parser.parse_args()

    adrs = collect_adrs(ADR_DIR)
    content = render_index(adrs)

    if args.check:
        if INDEX_FILE.exists() and INDEX_FILE.read_text(encoding="utf-8") == content:
            print(f"OK   {INDEX_FILE} is in sync with {len(adrs)} ADRs.")
            return 0
        print(
            f"DRIFT {INDEX_FILE} is out of date.\n"
            f"      Regenerate with: make regenerate-adr-index && git add {INDEX_FILE}",
            file=sys.stderr,
        )
        return 1

    INDEX_FILE.write_text(content, encoding="utf-8")
    print(f"WROTE {INDEX_FILE} ({len(adrs)} ADRs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
